### ISSUE TITLE
RSS: Link to article is not working

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/Siberian#668]
Even after update to 4.16.10 the link "Read full article" is dead. I am testing in webApp, this should work without republish.

I had this reply:
Read full article link is fixed in 4.16.10 (missing from the release note)
It is NOT fixed.
Firefox shows me the following error in the script, if that helps any.
TypeError: e.data.split is not a function app.bundle-min.js:2000:12727

**Comment by Slicit** [comment]
It's still bugged in WebApp, not in Native apps (as said you previously)

Fix for WebApp is scheduled in 4.16.11.

WebApps & Native apps doesn't behave the same for Links (external, new window, etc ...)

**Comment by grafixpress** [comment]
OK Slicit,
would be nice if this was mentioned in release note. :-)
Thank you
Thomas
