### ISSUE TITLE
RSS feeds: content is not refreshed.

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/Siberian#496]
When opening a RSS feed, old content is shown. The content is not refreshed at opening. There is no pull to refresh.
The only way to refresh is to click on any content and go back. Then the list is refreshed.
For any news RSS feeds this is unbearable.
I am on latest version. In previous versions the refresh worked fine when opening a feed.
So I assume this is a bug.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by Slicit** [comment]
As said RSS completely re-done in 4.16.x so not relevant anymore.

**Comment by grafixpress** [comment]
This issue is fixed and works fine, congraz.
But, since the update that fixed the issue, the link "Read full article" is dead.
That makes the module pretty useless.
Do I have to open a new thread, Alex?
Thomas

**Comment by Slicit** [comment]
Read full article link is fixed in 4.16.10 (missing from the release note)

**Comment by grafixpress** [comment]
Sorrty but no. Not fixed. Still dead after update to 4.16.10
Cache cleared.

**Comment by Slicit** [comment]
Apps must be updated and/or republished.

**Comment by grafixpress** [comment]
The link is live, but the page doesn´t open. I am testing on webApp

**Comment by grafixpress** [comment]
Maybe this helps
TypeError: e.data.split is not a function app.bundle-min.js:2000:12727

**Comment by userdevel** [comment]
@grafixpress it is solved now?

**Comment by Slicit** [comment]
Nope, working in WebApp as expected.

https://youtu.be/buNEcSwL9bc
